# Generated by Django 5.0 on 2023-12-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gas_price', models.FloatField()),
                ('transaction_speed', models.CharField(max_length=50)),
            ],
        ),
    ]
